spring:
  application:
    name: BlogManagement

  security:
    user:
      name: nicole
      password: nicole1234!

  datasource:
    driver-class-name: org.postgresql.Driver
    password: Nicole0509
    username: postgres
    url: jdbc:postgresql://localhost:5432/blog_management

  mongodb:
    uri: mongodb://localhost:27017/blog_management

server:
  port: 8081

management:
  endpoints:
    web:
      exposure:
        include: "*"

      base-path: /actuator

  endpoint:
    health:
      show-details: always

    env:
      show-values: never