spring:
  application:
    name: BlogManagement

  datasource:
    driver-class-name: org.postgresql.Driver
    password: Nicole0509
    username: postgres
    url: jdbc:postgresql://localhost:5432/blog_management

  jpa:
    properties:
      hibernate:
        format_sql: true
#    show-sql: true
    hibernate:
      ddl-auto: update

  mongodb:
    uri: mongodb://localhost:27017/blog_management

server:
  port: 8081

management:
  endpoints:
    web:
      exposure:
        include: "*"

      base-path: /actuator

  endpoint:
    health:
      show-details: always

    env:
      show-values: never

authentication:
  secret:
    key: owT1xfpF8VX4k9gqAZCDbQP9z4yYiOYntjxe1AXZmEM=ELSW60cNyz8pBj26aTe4IU90IqPHSVBft4T8MQXiLR8=